### ISSUE TITLE
Hinzufügen der jeweiligen Projekt-Homepage

### ISSUE THREAD

**Issue by mnul** [Yaoric/FAQ-RaspberryPi#1]
Hi,
du könntest zu den jeweiligen Projekten noch die dazugehörige Homepage (evtl auch Link aufs Docker Hub) dazu nehmen. Dann wird es vollständiger.

**Comment by Yaoric** [comment]
Soweit es mir unterkommt, füge ich sie hinzu. 
Die Seite darf auch gern editiert werden.
