### ISSUE TITLE
Anwendungsfälle fürs Wiki

### ISSUE THREAD

**Issue by ghost** [Yaoric/FAQ-RaspberryPi#2]
Hi,

hier zwei Anwendungsfälle, die noch in deiner Liste fehlen:

Node-Red -> https://nodered.org/docs/getting-started/raspberrypi

Rezeptedatenbank -> https://docs.tandoor.dev/install/manual/

Übrigens: Du schreibst unten auf deiner Wiki-Seite Anwendungsfälle, dass man die gerne editieren kann, das ist aber nicht so einfach möglich.

Grüße
René

**Comment by Yaoric** [comment]
> Du schreibst unten auf deiner Wiki-Seite Anwendungsfälle, dass man die gerne editieren kann, das ist aber nicht so einfach möglich.

Ich schau mal, ob ich ein Flag vergessen habe zu setzen. In den anderen Wikiseiten (bspw. Homematic) klappt es ja.

**Comment by Yaoric** [comment]
Ja, das öffentliche Editieren war noch deaktiviert, sollte jetzt gehen. Danke für den Hinweis!
